# Generated by Django 3.1 on 2021-03-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='events',
            field=models.ManyToManyField(related_name='organizer', to='webapp.Event'),
        ),
    ]
