# Generated by Django 3.1 on 2021-03-23 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizer',
            old_name='requests',
            new_name='request',
        ),
        migrations.RemoveField(
            model_name='organizer',
            name='event',
        ),
        migrations.RemoveField(
            model_name='user',
            name='request',
        ),
        migrations.AddField(
            model_name='event',
            name='event_organizer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.organizer'),
        ),
        migrations.AddField(
            model_name='request',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.user'),
        ),
    ]
