# Generated by Django 3.1 on 2021-03-24 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20210324_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventrequest',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='event_requests', to='webapp.event'),
        ),
    ]
