# Generated by Django 3.1 on 2021-03-23 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20210323_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator',
            name='request',
        ),
    ]
