# Generated by Django 3.1 on 2021-03-24 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20210324_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='organizer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_organizer', to='webapp.user'),
        ),
    ]
