# Generated by Django 3.1 on 2021-03-23 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_remove_administrator_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
