# Generated by Django 3.1 on 2021-03-23 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_request_isdeleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='time_Sent',
            new_name='time_sent',
        ),
    ]
