# Generated by Django 3.1 on 2021-03-23 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20210323_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.user'),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='organizer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.user'),
        ),
    ]
