# Generated by Django 3.1 on 2021-03-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20210323_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='isCanceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
