# Generated by Django 3.1 on 2021-03-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20210323_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='isFinished',
            field=models.BooleanField(default=False),
        ),
    ]
